#!/usr/bin/env python3
"""Generate the resident agent's native operation catalogue snapshot."""

from __future__ import annotations

import argparse
import json
import sys
import types
from pathlib import Path


def load_catalog(fork_src: Path) -> dict:
    package = types.ModuleType("yunohost")
    package.__path__ = [str(fork_src)]
    sys.modules.setdefault("yunohost", package)
    from yunohost.nostr_operations import operation_catalog

    return operation_catalog()


def render(document: dict) -> str:
    payload = json.dumps(document, sort_keys=True, separators=(",", ":"))
    return """// Code generated by scripts/generate_operation_registry.py; DO NOT EDIT.
package agent

const generatedCatalogJSON = %s
const GeneratedCatalogDigest = %s
""" % (json.dumps(payload), json.dumps(document["digest"]))


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--fork-src", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    rendered = render(load_catalog(args.fork_src.resolve()))
    if args.check:
        if not args.output.is_file() or args.output.read_text() != rendered:
            print(f"generated registry is stale: {args.output}", file=sys.stderr)
            return 1
        return 0
    args.output.write_text(rendered)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
